version: 2

build:
  os: "ubuntu-lts-latest"
  tools:
    python: "3.13"

submodules:
  include: all
  recursive: true

sphinx:
  builder: dirhtml
  configuration: conf.py
  fail_on_warning: false

python:
  install:
   - requirements: requirements.txt

formats:
- pdf
- epub


